// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('add_discussion_topic', function() {
  //this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it.only('add_discussion_topic', async function() {
    await driver.get("https://school.moodledemo.net/my/courses.php")
    await driver.manage().window().setRect({ width: 1096, height: 700 })
    await driver.findElement(By.linkText("Log in")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.linkText("My courses")).click()
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("critical")
    await driver.sleep(5000)
    await driver.findElement(By.css(".card-img")).click()
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.findElement(By.css("#module-1145 .aalink")).click()
    await driver.findElement(By.linkText("Add discussion topic")).click()
    await driver.findElement(By.id("id_subject")).click()
    await driver.findElement(By.id("id_subject")).sendKeys("thien")
    await driver.sleep(5000)
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.switchTo().frame(0)
    {
      const element = await driver.findElement(By.id("tinymce"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdskjfdsk</p>'}", element)
    }
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("id_advancedadddiscussion")).click()
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.executeScript("window.scrollTo(0,793.3333129882812)")
    await driver.executeScript("window.scrollTo(0,593.3333129882812)")
    await driver.sleep(5000)
    await driver.executeScript("window.scrollTo(0,500)")
    await driver.findElement(By.css(".fa-file-o")).click()
    await driver.sleep(5000)
    await driver
					.findElement(By.xpath("//input[@type='file']"))
					.sendKeys("C:\\\\Users\\\\ThinkPad\\\\Downloads\\\\Project #3 description.pdf");
    await driver.findElement(By.xpath("//button[contains(.,\'Upload this file\')]")).click()
    await driver.sleep(3000)
    await driver.findElement(By.id("id_submitbutton")).click()
    await driver.close()
  })
})
