// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Teacher create a new event', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('TC-004-001', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.linkText("Log in")).click()
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    {
      const element = await driver.findElement(By.css(".float-sm-right"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const elements = await driver.findElements(By.id("id_error_name"))
      assert(elements.length)
    }
  })
  it('TC-004-002', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 2000)
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class Meeting")
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Course']")).click()
    }
    await driver.findElement(By.xpath("//div[3]/input")).click()
    await driver.findElement(By.xpath("//div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/ul/li")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.switchTo().frame(0)
    await driver.switchTo().defaultContent()
    await driver.findElement(By.css(".form-check-inline:nth-child(9)")).click()
    {
      const element = await driver.findElement(By.id("id_timedurationminutes"))
      assert(await element.isEnabled())
    }
    await driver.findElement(By.id("id_timedurationminutes")).sendKeys("30")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-003', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_day")).click()
    await driver.findElement(By.id("id_timestart_month")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_month"))
      await dropdown.findElement(By.xpath("//option[. = 'November']")).click()
    }
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Course']")).click()
    }
    await driver.findElement(By.xpath("//div[3]/input")).click()
    await driver.findElement(By.xpath("//div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/ul/li")).click()
    await driver.findElement(By.linkText("Show more...")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("p")).click()
    {
      const element = await driver.findElement(By.id("tinymce"))
      await driver.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>fdsfdsffdsfsdf</p>'}", element)
    }
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("id_location")).click()
    await driver.findElement(By.id("id_location")).sendKeys("218 Ly Thuong Kiet")
    await driver.findElement(By.id("id_duration_2")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    {
      const elements = await driver.findElements(By.id("fgroup_id_error_durationgroup"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.id("fgroup_id_error_durationgroup")).getText() == "The duration in minutes you have entered is invalid. Please enter the duration in minutes greater than 0 or select no duration.")
  })
  it('TC-004-004', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class Meeting")
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Course']")).click()
    }
    await driver.findElement(By.xpath("//div[3]/input")).click()
    await driver.findElement(By.xpath("//div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[4]/div[2]/ul/li")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.switchTo().frame(0)
    await driver.switchTo().defaultContent()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-005', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_day")).click()
    await driver.findElement(By.id("id_timestart_month")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_month"))
      await dropdown.findElement(By.xpath("//option[. = 'November']")).click()
    }
    await driver.findElement(By.id("id_timestart_year")).click()
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.id("id_eventtype")).click()
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Course']")).click()
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    {
      const elements = await driver.findElements(By.xpath("//*[@id=\"id_error_courseid\"]"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.id("id_error_courseid")).getText() == "Select a course")
  })
  it('TC-004-006', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class Meeting")
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Group']")).click()
    }
    await driver.findElement(By.xpath("//div[5]/div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[5]/div[2]/ul/li")).click()
    await driver.findElement(By.id("id_groupid")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.switchTo().frame(0)
    await driver.findElement(By.css("p")).click()
    await driver.findElement(By.css(".form-check-inline:nth-child(9)")).click()
    await driver.findElement(By.id("id_timedurationminutes")).click()
    await driver.findElement(By.id("id_timedurationminutes")).sendKeys("30")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-007', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 822, height: 760 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class Meeting")
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Group']")).click()
    }
    await driver.findElement(By.xpath("//div[5]/div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[5]/div[2]/ul/li")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.findElement(By.css(".form-check-inline:nth-child(9)")).click()
    await driver.findElement(By.id("id_timedurationminutes")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    {
      const elements = await driver.findElements(By.id("fgroup_id_error_durationgroup"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.id("fgroup_id_error_durationgroup")).getText() == "The duration in minutes you have entered is invalid. Please enter the duration in minutes greater than 0 or select no duration.")
    {
      const elements = await driver.findElements(By.id("id_error_groupcourseid"))
      assert(!elements.length)
    }
    await driver.findElement(By.xpath("//div[5]/div[2]/div/div/div/button/span")).click()
    await driver.findElement(By.css(".userpicture")).click()
    await driver.findElement(By.linkText("Log out")).click()
  })
  it('TC-004-008', async function() {
    await driver.get("https://school.moodledemo.net/login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class Meeting")
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Group']")).click()
    }
    await driver.findElement(By.xpath("//div[5]/div[2]/div[3]/input")).click()
    await driver.findElement(By.xpath("//div[5]/div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[5]/div[2]/ul/li")).click()
    await driver.findElement(By.id("id_groupid")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 5000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-009', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_day")).click()
    await driver.findElement(By.id("id_timestart_month")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_month"))
      await dropdown.findElement(By.xpath("//option[. = 'November']")).click()
    }
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.id("id_eventtype")).click()
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Group']")).click()
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    {
      const elements = await driver.findElements(By.xpath("//*[@id=\"id_error_groupcourseid\"]"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.id("id_error_groupcourseid")).getText() == "Select a course")
  })
  it('TC-004-010', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.findElement(By.css(".login-wrapper")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_month")).click()
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.id("id_eventtype")).click()
    {
      const dropdown = await driver.findElement(By.id("id_eventtype"))
      await dropdown.findElement(By.xpath("//option[. = 'Group']")).click()
    }
    await driver.findElement(By.xpath("//div[5]/div[2]/div[3]/span")).click()
    await driver.findElement(By.xpath("//div[5]/div[2]/ul/li")).click()
    {
      const value = await driver.findElement(By.xpath("//*[@id=\"id_groupid\"]")).getAttribute("value")
      assert(value == "57")
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
  })
  it('TC-004-011', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.findElement(By.id("id_duration_2")).click()
    await driver.findElement(By.id("id_timedurationminutes")).click()
    await driver.findElement(By.id("id_timedurationminutes")).sendKeys("30")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-012', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_day")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_day"))
      await dropdown.findElement(By.xpath("//option[. = '2']")).click()
    }
    await driver.findElement(By.id("id_timestart_month")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_month"))
      await dropdown.findElement(By.xpath("//option[. = 'November']")).click()
    }
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
  })
  it('TC-004-013', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-014', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.linkText("Show more...")).click()
    {
      const element = await driver.findElement(By.id("id_repeats"))
      assert(!await element.isEnabled())
    }
    await driver.findElement(By.css(".form-check > label")).click()
    {
      const element = await driver.findElement(By.id("id_repeats"))
      assert(await element.isEnabled())
    }
    await driver.findElement(By.id("id_repeats")).sendKeys("-1")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.xpath("//td[contains(@data-original-title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li[last()-1]")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button[2]")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    assert(await driver.findElement(By.css("#fgroup_id_repeatgroup .form-check-inline:nth-child(1)")).getText() == "Also apply changes to the other 0 events in this repeat series")
    await driver.findElement(By.xpath("//body/div[5]/div")).click()
    await driver.findElement(By.xpath("//div[5]/div/div/div/div/button/span")).click()
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-015', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.linkText("Show more...")).click()
    {
      const element = await driver.findElement(By.id("id_repeats"))
      assert(!await element.isEnabled())
    }
    await driver.findElement(By.css(".form-check > label")).click()
    {
      const element = await driver.findElement(By.id("id_repeats"))
      assert(await element.isEnabled())
    }
    await driver.findElement(By.id("id_repeats")).sendKeys("2")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.xpath("//td[contains(@data-original-title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li[last()-1]")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button[2]")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    assert(await driver.findElement(By.css("#fgroup_id_repeatgroup .form-check-inline:nth-child(1)")).getText() == "Also apply changes to the other 1 events in this repeat series")
    await driver.findElement(By.xpath("//body/div[5]/div")).click()
    await driver.findElement(By.xpath("//div[5]/div/div/div/div/button/span")).click()
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-016', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.linkText("Show more...")).click()
    await driver.findElement(By.css(".form-check-inline:nth-child(9)")).click()
    await driver.findElement(By.id("id_timedurationminutes")).click()
    await driver.findElement(By.id("id_timedurationminutes")).sendKeys("-15")
    await driver.findElement(By.xpath("//div[5]/div/div/div/div[3]/button")).click()
    assert(await driver.findElement(By.id("fgroup_id_error_durationgroup")).getText() == "The duration in minutes you have entered is invalid. Please enter the duration in minutes greater than 0 or select no duration.")
    await driver.findElement(By.xpath("//div[5]/div[2]/div/div/div/button/span")).click()
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
  it('TC-004-017', async function() {
    await driver.get("https://school.moodledemo.net//login/index.php")
    await driver.manage().window().setRect({ width: 820, height: 759 })
    await driver.findElement(By.id("username")).click()
    await driver.findElement(By.id("username")).sendKeys("teacher")
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//a[contains(text(),\'Dashboard\')]")).click()
    vars["no_events_init"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_init"])
    await driver.findElement(By.css(".float-sm-right")).click()
    await driver.findElement(By.id("id_name")).click()
    await driver.findElement(By.id("id_name")).sendKeys("Class meeting")
    await driver.findElement(By.id("id_timestart_hour")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_hour"))
      await dropdown.findElement(By.xpath("//option[. = '06']")).click()
    }
    await driver.findElement(By.id("id_timestart_minute")).click()
    {
      const dropdown = await driver.findElement(By.id("id_timestart_minute"))
      await dropdown.findElement(By.xpath("//option[. = '00']")).click()
    }
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    await driver.findElement(By.css(".form-check-inline:nth-child(9)")).click()
    await driver.findElement(By.id("id_timedurationminutes")).click()
    await driver.findElement(By.id("id_timedurationminutes")).sendKeys("6 0")
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button")).click()
    await driver.wait(until.elementLocated(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")), 4000)
    vars["no_events_final"] = await driver.findElements(By.xpath("//td[contains(@title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li")).length
    console.log(vars["no_events_final"])
    vars["status"] = await driver.executeScript("return arguments[0] == 0 ? arguments[1] == 2 : arguments[0] == arguments[1] - 1", vars["no_events_init"],vars["no_events_final"])
    assert(vars["status"].toString() == "true")
    await driver.findElement(By.xpath("//td[contains(@data-original-title, \'Today\')]//div[@data-region=\"day-content\"]/ul/li[last()-1]")).click()
    await driver.findElement(By.xpath("//div[2]/div/div/div[3]/button[2]")).click()
    await driver.findElement(By.xpath("//a[contains(.,\'Show more...\')]")).click()
    {
      const value = await driver.findElement(By.xpath("//*[@id=\"id_timedurationuntil_hour\"]/option[contains(text(), \'7\')]")).getAttribute("value")
      assert(value == "isSelected")
    }
    await driver.findElement(By.xpath("//body/div[5]/div")).click()
    await driver.findElement(By.xpath("//div[5]/div/div/div/div/button/span")).click()
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.xpath("//a[contains(text(),\'Log out\')]")).click()
  })
})
