// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Edit_profile5', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('Edit_profile5', async function() {
    await driver.get("https://school.moodledemo.net/my/courses.php")
    await driver.manage().window().setRect({ width: 652, height: 720 })
    await driver.findElement(By.id("user-menu-toggle")).click()
    await driver.findElement(By.linkText("Profile")).click()
    await driver.findElement(By.linkText("Edit profile")).click()
    await driver.findElement(By.id("id_firstname")).click()
    vars["windowHandles"] = await driver.getAllWindowHandles()
    vars["tab1"] = await waitForWindow(2000)
    vars["root"] = await driver.getWindowHandle()
    await driver.sleep(3000)
    await driver.switchTo().window(vars["tab1"])
    await driver.findElement(By.xpath("//button[contains(text(), \'Log out\')]")).click()
    await driver.switchTo().window(vars["root"])
    await driver.findElement(By.id("id_firstname")).sendKeys("a")
    await driver.findElement(By.id("id_submitbutton")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("moodle")
    await driver.findElement(By.id("loginbtn")).click()
    await driver.findElement(By.id("id_firstname")).click()
    await driver.findElement(By.id("id_firstname")).sendKeys("a")
    await driver.findElement(By.css("#fitem_id_firstname > .col-md-3")).click()
    await driver.findElement(By.id("id_submitbutton")).click()
  })
})
